plugins:
  calf-nursery:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - help
    - heart
    - hold
    - label
    - lgtm
    - transfer-issue
    - trigger
    - verify-owners
    - wip
    - yuks
    - require-matching-label
    - release-note
    - override
  calf-nursery/test-infra:
    plugins:
    - config-updater

approve:
- repos:
  - calf-nursery/testapp
  # RequireSelfApproval requires PR authors to explicitly approve their PRs.
  # Otherwise the plugin assumes the author of the PR approves the changes in the PR.
  require_self_approval: true

  # A /lgtm from a single approver should not allow a PR to merge.
  lgtm_acts_as_approve: false

lgtm:
- repos:
  - calf-nursery/testapp
  store_tree_hash: true

override:
  allow_top_level_owners: true

require_matching_label:
  # triage configuration
  - missing_label: needs-triage
    org: calf-nursery
    issues: true
    prs: false
    regexp: ^triage/accepted$
    missing_comment: |
      This issue is currently awaiting triage.
      If org contributors determine this is a relevant issue, they will accept it by applying the `triage/accepted` label and provide further guidance.
      The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.

external_plugins:
  calf-nursery:
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request
    endpoint: http://cherrypicker
  calf-nursery/testapp:
  - name: needs-rebase
    events:
    - issue_comment
    - pull_request

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/prow/labels.yaml:
      name: label-config
    jobs/**/*.{yaml,yml}:
      name: job-config
      gzip: true